services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_dev.sql:/docker-entrypoint-initdb.d/init_dev.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mdg-net

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mdg-net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - frontend_data:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:5173:5173"
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data:
  frontend_data:

networks:
  mdg-net:
