name: Client-CI/CD
run-name: Build and deploy frontend @${{ github.actor }}
on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./client/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_CLIENT_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "client"
