name: Deploy

on:
  workflow_run:
    workflows: ["Client CI", "Server CI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "api"
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "client"
