name: Deploy

on:
  workflow_run:
    workflows: ["Client CI", "Server CI"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run deploy script
        run: ./deploy.sh
