name: API-CI/CD
run-name: Build and deploy backend @${{ github.actor }}
on:
  push:
    paths:
      - "api/**/*.go"
  pull_request:
    paths:
      - "api/**/*.go"
defaults:
  run:
    shell: bash
    working-directory: api/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Build
        run: make build
      - name: Test
        run: make test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "api"
